Add save command
CS2103AUG2016-W14-C4/main pull request #155
Opened 2016-10-24 09:06 UTC by l0g1cal

Fixes #153

2016-10-24 17:24 UTC, IanTeo requested changes

2016-10-24 17:24 UTC, IanTeo commented on src/main/java/seedu/taskitty/logic/commands/SaveCommand.java
> +    public static final String MESSAGE_USAGE = "This command saves data in TasKitty to a location of your choice, Meow!\n"
MESSAGE_USAGE is too long for us to fit. Try to cut it down to 1 or 2 lines. Just basic info. The rest of the info, the user will have to check the UserGuide

2016-10-24 17:24 UTC, IanTeo commented on src/main/java/seedu/taskitty/logic/commands/SaveCommand.java
> +    public CommandResult execute() {
Just wondering.. But does this save TasKitty into the folder specified once?
Or does it change the save folder destination permanently?

2016-10-24 19:45 UTC, l0g1cal commented on src/main/java/seedu/taskitty/logic/commands/SaveCommand.java
> +    public CommandResult execute() {
It changes it permanently, based on my tests

2016-10-25 03:14 UTC, IanTeo commented on src/main/java/seedu/taskitty/logic/commands/SaveCommand.java
> +    public CommandResult execute() {
Ok great

2016-10-25 03:14 UTC, IanTeo approved these changes

2016-10-25 05:12 UTC, IanTeo commented
Jia Wern, you can fix the merge conflicts and merge it.
I feel that "save" might be ambiguous for this command.
The user might feel that it is to save TasKitty, not choose the save location.
I can't really think of a better command though.. "storage"? Anyone else have comments? @yamidark  @JJ-Rachel

2016-10-25 07:24 UTC, l0g1cal commented
How about 'store'?

2016-10-25 07:55 UTC, IanTeo commented
fixes #155

2016-10-25 07:58 UTC, merged